### ISSUE TITLE
Error in the lag_mpm demo when running the run.py no files in the result/particles or result/armadillo

### ISSUE THREAD

**Issue by 123jjx321** [taichi-dev/meshtaichi#3]
H:\taichi\meshtaichi-main\lag_mpm\utils.py:32: UserWarning: Calling non-taichi function "len". Scope inside the function is not processed by the Taichi AST transformer. The function may not work as expected. Proceed with caution! Maybe you can consider turning it into a @ti.func?
  r_s = min(int(x * (len(__palette__) - 1)), len(__palette__) - 2)
H:\taichi\meshtaichi-main\lag_mpm\utils.py:32: UserWarning: Calling non-taichi function "len". Scope inside the function is not processed by the Taichi AST transformer. The function may not work as expected. Proceed with caution! Maybe you can consider turning it into a @ti.func?
  r_s = min(int(x * (len(__palette__) - 1)), len(__palette__) - 2)
H:\taichi\meshtaichi-main\lag_mpm\utils.py:34: UserWarning: Calling non-taichi function "len". Scope inside the function is not processed by the Taichi AST transformer. The function may not work as expected. Proceed with caution! Maybe you can consider turning it into a @ti.func?
  val = x * (len(__palette__) - 1) - r_s
[I 10/28/22 11:58:45.937 8076] [C:/Users/Administrator/actions-runner/_work/taichi/taichi/taichi/rhi/vulkan/vulkan_device_creator.cpp:pick_physical_device@394] Found Vulkan Device 0 (NVIDIA GeForce RTX 3060)
[I 10/28/22 11:58:45.937 8076] [C:/Users/Administrator/actions-runner/_work/taichi/taichi/taichi/rhi/vulkan/vulkan_device_creator.cpp:create_logical_device@462] Vulkan Device "NVIDIA GeForce RTX 3060" supports Vulkan 0 version 1.2.186
frame: 0
substep: 0
[W 10/28/22 11:58:51.867 15460] [C:/Users/Administrator/actions-runner/_work/taichi/taichi/taichi/transforms/type_check.cpp:visit@161] [$14513] Field index 0 not int32, casting into int32 implicitly

[W 10/28/22 11:58:51.867 15460] [C:/Users/Administrator/actions-runner/_work/taichi/taichi/taichi/transforms/type_check.cpp:visit@161] [$14515] Field index 0 not int32, casting into int32 implicitly

[W 10/28/22 11:58:51.867 15460] [C:/Users/Administrator/actions-runner/_work/taichi/taichi/taichi/transforms/type_check.cpp:visit@161] [$14543] Field index 0 not int32, casting into int32 implicitly

[W 10/28/22 11:58:51.867 15460] [C:/Users/Administrator/actions-runner/_work/taichi/taichi/taichi/transforms/type_check.cpp:visit@161] [$14571] Field index 0 not int32, casting into int32 implicitly

[W 10/28/22 11:58:51.867 15460] [C:/Users/Administrator/actions-runner/_work/taichi/taichi/taichi/transforms/type_check.cpp:visit@161] [$14728] Field index 0 not int32, casting into int32 implicitly

[W 10/28/22 11:58:51.867 15460] [C:/Users/Administrator/actions-runner/_work/taichi/taichi/taichi/transforms/type_check.cpp:visit@161] [$14736] Field index 0 not int32, casting into int32 implicitly

[W 10/28/22 11:58:51.867 15460] [C:/Users/Administrator/actions-runner/_work/taichi/taichi/taichi/transforms/type_check.cpp:visit@161] [$14744] Field index 0 not int32, casting into int32 implicitly

**Comment by g1n0st** [comment]
Do you have used `mkdir results` to create `results` folder (not `result`)?

**Comment by g1n0st** [comment]
I'll close this issue soon. Feel free to open it if you still have any questions! (FYI: Update to the latest Taichi version to eliminate these warnings.)
